#!/bin/bash
set -e

CUSTOM_PW="${APP_DB_PASSWORD}"
MIGRATOR_PW="${MIGRATOR_DB_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
  CREATE ROLE custom_app   WITH LOGIN PASSWORD '${CUSTOM_PW}';
  CREATE ROLE app_migrator WITH LOGIN PASSWORD '${MIGRATOR_PW}';

  CREATE DATABASE ${APP_DB_Name} OWNER app_migrator;

  REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
  REVOKE CONNECT ON DATABASE ${APP_DB_Name}  FROM PUBLIC;

  GRANT CONNECT ON DATABASE ${APP_DB_Name} TO custom_app, app_migrator;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DB_Name" <<-EOSQL
  ALTER SCHEMA public OWNER TO app_migrator;

  GRANT USAGE ON SCHEMA public TO custom_app;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO custom_app;
  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO custom_app;

  ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO custom_app;

  ALTER DEFAULT PRIVILEGES FOR ROLE app_migrator IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO custom_app;
EOSQL
