#!/bin/bash
set -e

AUTH_PW="${AUTH_DB_PASSWORD}"
MIGRATOR_PW="${MIGRATOR_DB_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
  CREATE ROLE auth_app     WITH LOGIN PASSWORD '${AUTH_PW}';
  CREATE ROLE auth_app_migrator WITH LOGIN PASSWORD '${MIGRATOR_PW}';

  CREATE DATABASE ${AUTH_DB_Name} OWNER auth_app_migrator;

  REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
  REVOKE CONNECT ON DATABASE ${AUTH_DB_Name} FROM PUBLIC;

  GRANT CONNECT ON DATABASE ${AUTH_DB_Name} TO auth_app, auth_app_migrator;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AUTH_DB_Name" <<-EOSQL
  ALTER SCHEMA public OWNER TO auth_app_migrator;

  GRANT USAGE ON SCHEMA public TO auth_app;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO auth_app;
  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO auth_app;

  ALTER DEFAULT PRIVILEGES FOR ROLE auth_app_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO auth_app;

  ALTER DEFAULT PRIVILEGES FOR ROLE auth_app_migrator IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO auth_app;
EOSQL
